title: Toni
author:
  name: Toni Latorre
  email: toni.lc@pm.me
description: "Toni Latorre"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tonilatorrec.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: tonilatorrec

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  social_links:
    github: tonilatorrec

sass:
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
