#!/bin/sh

set -e

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
cd "$repo_root"

"$script_dir/build"

if test -e "$repo_root/_site/index.html";then
  echo "It builds!"
else
  echo "Huh. That's odd. The site doesn't seem to build."
  exit 1
fi
